e1=new.env()
load('price_raw.RData',e1)
dce=e1$dce
rm(e1)
dce_df=clean(dce)
saveRDS(rearrange(dce_df),file='dce_rearrange.rds')
dce_xts=clean(dce,T)
save.image('dce.RData')
rm(dce,dce_df,dce_xts)
gc()


e1=new.env()
load('price_raw.RData',e1)
rbt=e1$rbt
rm(e1)
rbt_df=clean(rbt)
saveRDS(rearrange(rbt_df),file='rbt_rearrange.rds')
rbt_xts=clean(rbt,T)
save.image('rbt.RData')
rm(rbt,rbt_df,rbt_xts)
gc()


e1=new.env()
load('price_raw.RData',e1)
cu=e1$cu
rm(e1)
cu_df=clean(cu)
saveRDS(rearrange(cu_df),file='cu_rearrange.rds')
cu_xts=clean(cu,T)
save.image('cu.RData')
rm(cu,cu_df,cu_xts)
gc()

e1=new.env()
load('price_raw.RData',e1)
ioe=e1$ioe
rm(e1)
ioe_df=clean(ioe)
saveRDS(rearrange(ioe_df),file='ioe_rearrange.rds')
ioe_xts=clean(ioe,T)
save.image('ioe.RData')
rm(ioe,ioe_df,ioe_xts)
gc()

e1=new.env()
load('price_raw.RData',e1)
kee=e1$kee
rm(e1)
kee_df=clean(kee)
saveRDS(rearrange(kee_df),file='kee_rearrange.rds')
kee_xts=clean(kee,T)
save.image('kee.RData')
rm(kee,kee_df,kee_xts)
gc()

e1=new.env()
load('price_raw.RData',e1)
xii=e1$xii
rm(e1)
xii_df=clean(xii)
saveRDS(rearrange(xii_df),file='xii_rearrange.rds')
xii_xts=clean(xii,T)
save.image('xii.RData')
rm(xii,xii_df,xii_xts)
gc()

e1=new.env()
load('price_raw.RData',e1)
rt=e1$rt
rm(e1)
rt_df=clean(rt)
saveRDS(rearrange(rt_df),file='rt_rearrange.rds')
rt_xts=clean(rt,T)
save.image('rt.RData')
rm(rt,rt_df,rt_xts)
gc()

e1=new.env()
load('price_raw.RData',e1)
zna=e1$zna
rm(e1)
zna_df=clean(zna)
saveRDS(rearrange(zna_df),file='zna_rearrange.rds')
zna_xts=clean(zna,T)
save.image('zna.RData')
rm(zna,zna_df,zna_xts)
gc()

e1=new.env()
load('price_raw.RData',e1)
pt=e1$pt
rm(e1)
pt_df=clean(pt)
saveRDS(rearrange(pt_df),file='pt_rearrange.rds')
pt_xts=clean(pt,T)
save.image('pt.RData')
rm(pt,pt_df,pt_xts)
gc()

e1=new.env()
load('price_raw.RData',e1)
ckc=e1$ckc
rm(e1)
ckc_df=clean(ckc)
saveRDS(rearrange(ckc_df),file='ckc_rearrange.rds')
ckc_xts=clean(ckc,T)
save.image('ckc.RData')
rm(ckc,ckc_df,ckc_xts)
gc()